name: "Setup Terraform Cloud"
description: "Setup Terraform Cloud for the workflow"

inputs:
  message:
    description: "Message to print"
    required: false
    default: "Hello, world!"


runs:
  using: "composite"
  steps:
    - run: echo "${{ inputs.message }}"
      shell: bash